package cpu

type addressMode int

const (
	addrModeZeroPageX addressMode = iota
	addrModeZeroPageY
	addrModeAbsoluteX
	addrModeAbsoluteY
	addrModeIndexIndirX
	addrModeIndirIndexY
	addrModeImplied
	addrModeAccumulator
	addrModeImmediate
	addrModeZeroPage
	addrModeAbsolute
	addrModeRelative
	addrModeIndirect
)

type instruction struct {
	mnemonic string
	addrMode addressMode
	bytes    int
	cycles   int
	fn       func(*Cpu, *instruction)
}

var opcodes = [256]instruction{
	0x00: {"BRK", addrModeImplied, 2, 7, (*Cpu).forceBreak},
	0x01: {"ORA", addrModeIndexIndirX, 2, 6, (*Cpu).bitwiseOr},
	0x05: {"ORA", addrModeZeroPage, 2, 3, (*Cpu).bitwiseOr},
	0x06: {"ASL", addrModeZeroPage, 2, 5, (*Cpu).arithmeticShiftLeft},
	0x08: {"PHP", addrModeImplied, 1, 3, (*Cpu).pushProcessorStatus},
	0x09: {"ORA", addrModeImmediate, 2, 2, (*Cpu).bitwiseOr},
	0x0A: {"ASL", addrModeAccumulator, 1, 2, (*Cpu).arithmeticShiftLeft},
	0x0D: {"ORA", addrModeAbsolute, 3, 4, (*Cpu).bitwiseOr},
	0x0E: {"ASL", addrModeAbsolute, 3, 6, (*Cpu).arithmeticShiftLeft},
	0x10: {"BPL", addrModeRelative, 2, 2, (*Cpu).branchIfPlus},
	0x11: {"ORA", addrModeIndirIndexY, 2, 5, (*Cpu).bitwiseOr},
	0x15: {"ORA", addrModeZeroPageX, 2, 4, (*Cpu).bitwiseOr},
	0x16: {"ASL", addrModeZeroPageX, 2, 6, (*Cpu).arithmeticShiftLeft},
	0x18: {"CLC", addrModeImplied, 1, 2, (*Cpu).clearCarry},
	0x19: {"ORA", addrModeAbsoluteY, 3, 4, (*Cpu).bitwiseOr},
	0x1D: {"ORA", addrModeAbsoluteX, 3, 4, (*Cpu).bitwiseOr},
	0x1E: {"ASL", addrModeAbsoluteX, 3, 7, (*Cpu).arithmeticShiftLeft},
	0x20: {"JSR", addrModeAbsolute, 3, 6, (*Cpu).jumpToSubroutine},
	0x21: {"AND", addrModeIndexIndirX, 2, 6, (*Cpu).bitwiseAnd},
	0x24: {"BIT", addrModeZeroPage, 2, 3, (*Cpu).bitTest},
	0x25: {"AND", addrModeZeroPage, 2, 3, (*Cpu).bitwiseAnd},
	0x26: {"ROL", addrModeZeroPage, 2, 5, (*Cpu).rotateLeft},
	0x28: {"PLP", addrModeImplied, 1, 4, (*Cpu).pullProcessorStatus},
	0x29: {"AND", addrModeImmediate, 2, 2, (*Cpu).bitwiseAnd},
	0x2A: {"ROL", addrModeAccumulator, 1, 2, (*Cpu).rotateLeft},
	0x2C: {"BIT", addrModeAbsolute, 3, 4, (*Cpu).bitTest},
	0x2D: {"AND", addrModeAbsolute, 3, 4, (*Cpu).bitwiseAnd},
	0x2E: {"ROL", addrModeAbsolute, 3, 6, (*Cpu).rotateLeft},
	0x30: {"BMI", addrModeRelative, 2, 2, (*Cpu).branchIfMinus},
	0x31: {"AND", addrModeIndirIndexY, 2, 5, (*Cpu).bitwiseAnd},
	0x35: {"AND", addrModeZeroPageX, 2, 4, (*Cpu).bitwiseAnd},
	0x36: {"ROL", addrModeZeroPageX, 2, 6, (*Cpu).rotateLeft},
	0x38: {"SEC", addrModeImplied, 1, 2, (*Cpu).setCarry},
	0x39: {"AND", addrModeAbsoluteY, 3, 4, (*Cpu).bitwiseAnd},
	0x3D: {"AND", addrModeAbsoluteX, 3, 4, (*Cpu).bitwiseAnd},
	0x3E: {"ROL", addrModeAbsoluteX, 3, 7, (*Cpu).rotateLeft},
	0x40: {"RTI", addrModeImplied, 1, 6, (*Cpu).returnFromInterrupt},
	0x41: {"EOR", addrModeIndexIndirX, 2, 6, (*Cpu).bitwiseXor},
	0x45: {"EOR", addrModeZeroPage, 2, 3, (*Cpu).bitwiseXor},
	0x46: {"LSR", addrModeZeroPage, 2, 5, (*Cpu).logicalShiftRight},
	0x48: {"PHA", addrModeImplied, 1, 3, (*Cpu).pushA},
	0x49: {"EOR", addrModeImmediate, 2, 2, (*Cpu).bitwiseXor},
	0x4A: {"LSR", addrModeAccumulator, 1, 2, (*Cpu).logicalShiftRight},
	0x4C: {"JMP", addrModeAbsolute, 3, 3, (*Cpu).jump},
	0x4D: {"EOR", addrModeAbsolute, 3, 4, (*Cpu).bitwiseXor},
	0x4E: {"LSR", addrModeAbsolute, 3, 6, (*Cpu).logicalShiftRight},
	0x50: {"BVC", addrModeRelative, 2, 2, (*Cpu).branchIfOverflowClear},
	0x51: {"EOR", addrModeIndirIndexY, 2, 5, (*Cpu).bitwiseXor},
	0x55: {"EOR", addrModeZeroPageX, 2, 4, (*Cpu).bitwiseXor},
	0x56: {"LSR", addrModeZeroPageX, 2, 6, (*Cpu).logicalShiftRight},
	0x58: {"CLI", addrModeImplied, 1, 2, (*Cpu).clearInterruptDisable},
	0x59: {"EOR", addrModeAbsoluteY, 3, 4, (*Cpu).bitwiseXor},
	0x5D: {"EOR", addrModeAbsoluteX, 3, 4, (*Cpu).bitwiseXor},
	0x5E: {"LSR", addrModeAbsoluteX, 3, 7, (*Cpu).logicalShiftRight},
	0x60: {"RTS", addrModeImplied, 1, 6, (*Cpu).returnFromSubroutine},
	0x61: {"ADC", addrModeIndexIndirX, 2, 6, (*Cpu).addWithCarry},
	0x65: {"ADC", addrModeZeroPage, 2, 3, (*Cpu).addWithCarry},
	0x66: {"ROR", addrModeZeroPage, 2, 5, (*Cpu).rotateRight},
	0x68: {"PLA", addrModeImplied, 1, 4, (*Cpu).pullA},
	0x69: {"ADC", addrModeImmediate, 2, 2, (*Cpu).addWithCarry},
	0x6A: {"ROR", addrModeAccumulator, 1, 2, (*Cpu).rotateRight},
	0x6C: {"JMP", addrModeIndirect, 3, 5, (*Cpu).jump},
	0x6D: {"ADC", addrModeAbsolute, 3, 4, (*Cpu).addWithCarry},
	0x6E: {"ROR", addrModeAbsolute, 3, 6, (*Cpu).rotateRight},
	0x70: {"BVS", addrModeRelative, 2, 2, (*Cpu).branchIfOverflowSet},
	0x71: {"ADC", addrModeIndirIndexY, 2, 5, (*Cpu).addWithCarry},
	0x75: {"ADC", addrModeZeroPageX, 2, 4, (*Cpu).addWithCarry},
	0x76: {"ROR", addrModeZeroPageX, 2, 6, (*Cpu).rotateRight},
	0x78: {"SEI", addrModeImplied, 1, 2, (*Cpu).setInterruptDisable},
	0x79: {"ADC", addrModeAbsoluteY, 3, 4, (*Cpu).addWithCarry},
	0x7D: {"ADC", addrModeAbsoluteX, 3, 4, (*Cpu).addWithCarry},
	0x7E: {"ROR", addrModeAbsoluteX, 3, 7, (*Cpu).rotateRight},
	0x81: {"STA", addrModeIndexIndirX, 2, 6, (*Cpu).storeA},
	0x84: {"STY", addrModeZeroPage, 2, 3, (*Cpu).storeY},
	0x85: {"STA", addrModeZeroPage, 2, 3, (*Cpu).storeA},
	0x86: {"STX", addrModeZeroPage, 2, 3, (*Cpu).storeX},
	0x88: {"DEY", addrModeImplied, 1, 2, (*Cpu).decrementY},
	0x8A: {"TXA", addrModeImplied, 1, 2, (*Cpu).transferXToA},
	0x8C: {"STY", addrModeAbsolute, 3, 4, (*Cpu).storeY},
	0x8D: {"STA", addrModeAbsolute, 3, 4, (*Cpu).storeA},
	0x8E: {"STX", addrModeAbsolute, 3, 4, (*Cpu).storeX},
	0x90: {"BCC", addrModeRelative, 2, 2, (*Cpu).branchIfCarryClear},
	0x91: {"STA", addrModeIndirIndexY, 2, 6, (*Cpu).storeA},
	0x94: {"STY", addrModeZeroPageX, 2, 4, (*Cpu).storeY},
	0x95: {"STA", addrModeZeroPageX, 2, 4, (*Cpu).storeA},
	0x96: {"STX", addrModeZeroPageY, 2, 4, (*Cpu).storeX},
	0x98: {"TYA", addrModeImplied, 1, 2, (*Cpu).transferYToA},
	0x99: {"STA", addrModeAbsoluteY, 3, 5, (*Cpu).storeA},
	0x9A: {"TXS", addrModeImplied, 1, 2, (*Cpu).transferXToStackPointer},
	0x9D: {"STA", addrModeAbsoluteX, 3, 5, (*Cpu).storeA},
	0xA0: {"LDY", addrModeImmediate, 2, 2, (*Cpu).loadY},
	0xA1: {"LDA", addrModeIndexIndirX, 2, 6, (*Cpu).loadA},
	0xA2: {"LDX", addrModeImmediate, 2, 2, (*Cpu).loadX},
	0xA4: {"LDY", addrModeZeroPage, 2, 3, (*Cpu).loadY},
	0xA5: {"LDA", addrModeZeroPage, 2, 3, (*Cpu).loadA},
	0xA6: {"LDX", addrModeZeroPage, 2, 3, (*Cpu).loadX},
	0xA8: {"TAY", addrModeImplied, 1, 2, (*Cpu).transferAToY},
	0xA9: {"LDA", addrModeImmediate, 2, 2, (*Cpu).loadA},
	0xAA: {"TAX", addrModeImplied, 1, 2, (*Cpu).transferAToX},
	0xAC: {"LDY", addrModeAbsolute, 3, 4, (*Cpu).loadY},
	0xAD: {"LDA", addrModeAbsolute, 3, 4, (*Cpu).loadA},
	0xAE: {"LDX", addrModeAbsolute, 3, 4, (*Cpu).loadX},
	0xB0: {"BCS", addrModeRelative, 2, 2, (*Cpu).branchIfCarrySet},
	0xB1: {"LDA", addrModeIndirIndexY, 2, 5, (*Cpu).loadA},
	0xB4: {"LDY", addrModeZeroPageX, 2, 4, (*Cpu).loadY},
	0xB5: {"LDA", addrModeZeroPageX, 2, 4, (*Cpu).loadA},
	0xB6: {"LDX", addrModeZeroPageY, 2, 4, (*Cpu).loadX},
	0xB8: {"CLV", addrModeImplied, 1, 2, (*Cpu).clearOverflow},
	0xB9: {"LDA", addrModeAbsoluteY, 3, 4, (*Cpu).loadA},
	0xBA: {"TSX", addrModeImplied, 1, 2, (*Cpu).transferStackPointerToX},
	0xBC: {"LDY", addrModeAbsoluteX, 3, 4, (*Cpu).loadY},
	0xBD: {"LDA", addrModeAbsoluteX, 3, 4, (*Cpu).loadA},
	0xBE: {"LDX", addrModeAbsoluteY, 3, 4, (*Cpu).loadX},
	0xC0: {"CPY", addrModeImmediate, 2, 2, (*Cpu).compareY},
	0xC1: {"CPA", addrModeIndexIndirX, 2, 6, (*Cpu).compareA},
	0xC4: {"CPY", addrModeZeroPage, 2, 3, (*Cpu).compareY},
	0xC5: {"CPA", addrModeZeroPage, 2, 3, (*Cpu).compareA},
	0xC6: {"DEC", addrModeZeroPage, 2, 5, (*Cpu).decrementMemory},
	0xC8: {"INY", addrModeImplied, 1, 2, (*Cpu).incrementY},
	0xC9: {"CMP", addrModeImmediate, 2, 2, (*Cpu).compareA},
	0xCA: {"DEX", addrModeImplied, 1, 2, (*Cpu).decrementX},
	0xCC: {"CPY", addrModeAbsolute, 3, 4, (*Cpu).compareY},
	0xCD: {"CMP", addrModeAbsolute, 3, 4, (*Cpu).compareA},
	0xCE: {"DEC", addrModeAbsolute, 3, 6, (*Cpu).decrementMemory},
	0xD0: {"BNE", addrModeRelative, 2, 2, (*Cpu).branchIfNotEqual},
	0xD1: {"CMP", addrModeIndirIndexY, 2, 5, (*Cpu).compareA},
	0xD5: {"CMP", addrModeZeroPageX, 2, 4, (*Cpu).compareA},
	0xD6: {"DEC", addrModeZeroPageX, 2, 6, (*Cpu).decrementMemory},
	0xD8: {"CLD", addrModeImplied, 1, 2, (*Cpu).clearDecimal},
	0xD9: {"CMP", addrModeAbsoluteY, 3, 4, (*Cpu).compareA},
	0xDD: {"CMP", addrModeAbsoluteX, 3, 4, (*Cpu).compareA},
	0xDE: {"DEC", addrModeAbsoluteX, 3, 7, (*Cpu).decrementMemory},
	0xE0: {"CPX", addrModeImmediate, 2, 2, (*Cpu).compareX},
	0xE1: {"SBC", addrModeIndexIndirX, 2, 6, (*Cpu).subtractWithCarry},
	0xE4: {"CPX", addrModeZeroPage, 2, 3, (*Cpu).compareX},
	0xE5: {"SBC", addrModeZeroPage, 2, 3, (*Cpu).subtractWithCarry},
	0xE6: {"INC", addrModeZeroPage, 2, 5, (*Cpu).incrementMemory},
	0xE8: {"INX", addrModeImplied, 1, 2, (*Cpu).incrementX},
	0xE9: {"SBC", addrModeImmediate, 2, 2, (*Cpu).subtractWithCarry},
	0xEA: {"NOP", addrModeImplied, 1, 2, (*Cpu).noOperation},
	0xEC: {"CPX", addrModeAbsolute, 3, 4, (*Cpu).compareX},
	0xED: {"SBC", addrModeAbsolute, 3, 4, (*Cpu).subtractWithCarry},
	0xEE: {"INC", addrModeAbsolute, 3, 6, (*Cpu).incrementMemory},
	0xF0: {"BEQ", addrModeRelative, 2, 2, (*Cpu).branchIfEqual},
	0xF1: {"SBC", addrModeIndirIndexY, 2, 5, (*Cpu).subtractWithCarry},
	0xF5: {"SBC", addrModeZeroPageX, 2, 4, (*Cpu).subtractWithCarry},
	0xF6: {"INC", addrModeZeroPageX, 2, 6, (*Cpu).incrementMemory},
	0xF8: {"SED", addrModeImplied, 1, 2, (*Cpu).setDecimal},
	0xF9: {"SBC", addrModeAbsoluteY, 3, 4, (*Cpu).subtractWithCarry},
	0xFD: {"SBC", addrModeAbsoluteX, 3, 4, (*Cpu).subtractWithCarry},
	0xFE: {"INC", addrModeAbsoluteX, 3, 7, (*Cpu).incrementMemory},
}
